# Generated by Django 3.1.2 on 2020-10-26 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deptid', models.IntegerField()),
                ('deptname', models.CharField(max_length=256)),
                ('dpthod', models.CharField(max_length=256)),
                ('location', models.CharField(max_length=256)),
            ],
        ),
    ]
