# Generated by Django 3.1.2 on 2020-10-26 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='College',
            new_name='Collegetb',
        ),
    ]
